CREATE USER Lilia1 WITH PASSWORD 'lilia';
CREATE USER Lilia2 WITH PASSWORD 'lilia2';
\du
CREATE DATABASE my_db;
GRANT ALL PRIVILEGES ON DATABASE my_db to Lilia1;
GRANT VIEW ON DATABASE my_db to Lilia2;
GRANT EDIT ON DATABASE my_db to Lilia2;
\l
\du
ALTER USER Lilia1 PASSWORD 'lilia1506';
ALTER USER Lilia2 PASSWORD 'lilia11';
